language: cpp

os:
  - linux

git:
  submodules: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libx11-dev
      - libgl1-mesa-dev

compiler:
  - gcc
  #- clang
# Bullet compiling fails with CLang, so we not use it yet..

before_install:
  - git submodule update --init
  - echo $LANG
  - echo $LC_ALL
  # CMake repo
  - echo "yes" | sudo add-apt-repository ppa:andykimpe/cmake3
  - sudo apt-get update -qq

install:
  # Install CMake 3.0
  - sudo apt-get -y install cmake
  - cmake --version
  # Enforces GCC 4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # Enforces CLang 3.7
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi
    # Install OpenAL and GLEW
  - sudo apt-get -q -y install libglew-dev libopenal-dev
    # Install and build gtest
  #- sudo apt-get -q -y install libgtest-dev
  #- BUILD_PATH=$(pwd)
  #- cd /usr/src/gtest
  #- sudo cmake CMakeLists.txt
  #- sudo make
  #- GTEST_ROOT=/usr/src/gtest
  #- export GTEST_ROOT
  #- cd $BUILD_PATH

before_script:
  - pwd
  - mkdir build
  - cd build

script:
  - echo "Building dependencies (bullet) and installing it"
  - cmake ..
  - make
  - sudo make install
  - echo "Building TEC"
  - rm -f cmakecache.txt
  - cmake ..
  - make
  - ls
    #- ./TCCTests

notifications:
  #email:
    #- my.mail@bar.com
  # I can also set up Glitch to output build results as well if we don't want the travis bot join/part spam
  irc:
    channels:
      - "chat.freenode.net#project-trillek"
      - "chat.freenode.net#trillek"
    on_success: change
    on_failure: always
