language: cpp
os:
  - linux

sudo: false

cache:
    directories:
        - $HOME/cmake

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libx11-dev
      - libgl1-mesa-dev
      - xorg-dev
      - libglu1-mesa-dev
      - libglew-dev
      - libopenal-dev

compiler:
  - gcc
  #- clang
# Bullet compiling fails with CLang, so we not use it yet..

before_install:
  - sudo apt-get update -qq
  - git submodule update --init
  # Enforces GCC 4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # Enforces CLang 3.7
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi
  - echo $LANG
  - echo $LC_ALL
    # Grabs Cmake 3.2
  - ./travis/install_cmake.sh
  - ls $HOME/cmake/
  - export PATH=$HOME/cmake/:$HOME/cmake/bin/:$PATH
  - cmake --version

install:

before_script:
  - pwd
  - mkdir build
  - cd build

script:
  - echo "Building dependencies (bullet) and installing it"
  - cmake ..
  - make
  - sudo make install
  - echo "Building TEC"
  - rm -f cmakecache.txt
  - cmake -DBUILD_TESTS_TEC=True ..
  - make
  - ls
  - ./bin/UNIT_TEST

notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#project-trillek"
#      - "chat.freenode.net#trillek"
#    on_success: change
#    on_failure: always
